version: 2
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: 
            name: Segue
            command: npm run build
  serve:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: 
            name: Segue
            command: npm run serve
workflows:
  test_my_app:
    jobs:
      - build
      - serve:
        requires:
          - build