stages: 
    - build
    - test
    - pack
    - deploy_dev
    - deploy_demo

build_job:
    stage: build
    only:
        - merge_requests
        - develop
        - demo
    script:
        - npm install
        - npm run build
    tags:
        - Node_Build

test_job:
    stage: test
    only:
        - merge_requests
        - develop
        - demo
    script:
        - npm install
        - npm run test
    tags:
        - Node_Build
    dependencies:
        - build_job

pack_job:
    stage: pack
    only:
        - develop
        - demo
    script:
        - npm install
        - npm run build

    artifacts:
        expire_in: 1 day
        paths:
            - './dist/'
    tags:
        - Node_Build
    dependencies:
        - test_job

deploy_dev_job:
    stage: deploy_dev
    variables:
        GIT_STRATEGY: none
    only:
        - develop
    script:
        - xcopy "dist" "$env:CDN_HOMOLOG\$env:PASTA_DEPLOY\" /E /Y
    tags:
        - dev_build
    dependencies:
        - pack_job

deploy_demo_job:
    stage: deploy_demo
    variables:
        GIT_STRATEGY: none
    only:
        - demo
    script:
        - xcopy "dist" "$env:CDN_HOMOLOG\$env:PASTA_DEPLOY\" /E /Y
    tags:
        - dotnetframework
    dependencies:
        - pack_job
